apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    deployment:
      dnsPolicy: ClusterFirstWithHostNet
    hostNetwork: true
    ports:
      web:
        hostPort: 80
        containerPort: 80
        port: 80
        redirectTo: websecure
      websecure:
        hostPort: 443
        containerPort: 443
        port: 443
    service:
      type: ClusterIP
    securityContext:
      capabilities:
        drop: [ALL]
        add: [NET_BIND_SERVICE]
      readOnlyRootFilesystem: true
      runAsGroup: 0
      runAsNonRoot: false
      runAsUser: 0
